name: torch
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - numpy
  - pydantic
  - python>=3.8
  - pytorch>=1.11.0
  - scipy # for xitorch
  - pytest
  - pip:
      - tad-mctc
      - tad-multicharge
      - tad-dftd3
      - tad-dftd4
