name: dxtb
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - numpy
  - pydantic
  - python>=3.8
  - pytorch>=1.11.0
  - scipy # for xitorch
  - pytest
  - pip:
      - tad-dftd3==0.1.0
